src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateEmbauche = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $entreprise = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(?\DateTimeInterface $dateNaissance): self
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): self
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }


    public function getAge() {
        $now = new \DateTime();
        $interval = date_diff($this->dateNaissance, $now);
        return $interval->format("%Y");
    }


    public function __toString()
    {
        return $this->nom . " " . $this->prenom ;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }
}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('prenom', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control']
            ])
            ->add('dateEmbauche', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'form-control']
            ])
            ->add('ville', TextType::class, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('entreprise', EntityType::class, [
                'class' => Entreprise::class,
                'choice_label' => 'raisonSociale',
                'attr' => ['class' => 'form-control']
            ])
            ->add('submit', SubmitType::class, [
                'attr' => [ 'class' => 'btn btn-success']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;
use App\Entity\Employe;
use App\Form\EmployeType;
use Doctrine\Persistence\ManagerRegistry;
use PhpParser\Node\Expr\AssignOp\Mod;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class EmployeController extends AbstractController
{
    #[Route('/employe', name: 'app_employe')]
    public function index( ManagerRegistry $doctrine): Response
    {
        //recuperer les entreprise de la bdd
        $employes =  $doctrine->getRepository(Employe::class)->findBy([], ["nom" => "ASC"]);

        return $this->render('employe/index.html.twig', [
            'employes' => $employes
        ]);
    }

    #[Route('/employe/add', name: 'add_employe')]
    #[Route('/employe/{id}/edit', name: 'edit_employe')]
    public function add( ManagerRegistry $doctrine, Employe $employe = null, Request $request) : Response 
    {
        if(!$employe){
            $employe = New Employe();
        }

        $form = $this->createForm( EmployeType::class, $employe);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $employe = $form->getData();
            $entityManager = $doctrine->getManager();
            //prepare en équivalent PDO
            $entityManager->persist($employe);
            //insert into (execute)
            $entityManager->flush();

            return $this->redirectToRoute('app_employe');
        }

        return $this->render('employe/add.html.twig', [
            'formAddEmploye' => $form->createView(),
            'edit'=> $employe->getId()
        ]);
    }

    #[Route('/employe/{id}/delete', name: 'delete_employe')]
    public function delete( ManagerRegistry $doctrine, Employe $employe):Response
    {
        $entityManager = $doctrine->getManager();
        //enleve l'employe de la liste des employe
        $entityManager->remove($employe);
        //persist pas utile, flush, execute requete
        $entityManager->flush();

        return $this->redirectToRoute('app_employe');
    }

    #[Route('/employe/{id}', name: 'show_employe')]
    public function show(Employe $employe): Response 
    {
        return $this->render('employe/show.html.twig', [
            'employe' => $employe
        ]);
    }

}

templates/employe/add.html.twig
{% extends 'base.html.twig' %}

{% block title %} Le form employe {% endblock %}

{% block body %}

    {% if edit %}
    <h1> Editer un employé </h1>
        {% else %}
        <h1> Ajouter un employé </h1>
    {% endif %}

    {# {{ form(formAddEmploye) }} #}

    {{ form_start(formAddEmploye) }}
        {{ form_errors(formAddEmploye) }}
        <div class="rowform">
            {{ form_row(formAddEmploye.nom) }}
            {{ form_row(formAddEmploye.prenom) }}
        </div>
        <div class="rowform">
            {{ form_row(formAddEmploye.dateNaissance) }}
            {{ form_row(formAddEmploye.dateEmbauche) }}
        </div>
        <div class="rowform">
            {{ form_row(formAddEmploye.ville) }}
            {{ form_row(formAddEmploye.entreprise) }}
        </div>

        {{ form_row(formAddEmploye.submit, { 'label': 'Envoyer' }) }}
    {{ form_end(formAddEmploye) }}


{% endblock %}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Employés {% endblock %}

{% block body %}
    <h1>Liste des employés</h1>

    <a class="btn btn-primary" href="{{ path('add_employe')}}"> Ajouter un employe</a> <br>

    {% for employe in employes %}
        <a href="{{ path('show_employe', {'id': employe.id}) }}">{{ employe }} </a>
        <a class="btn btn-warning" href="{{ path('edit_employe', {'id': employe.id}) }}">Editer</a>
        <a class="btn btn-danger" href="{{ path('delete_employe', {'id': employe.id}) }}">Delete</a> <br>
    {% endfor %}
{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'un employé{% endblock %}

{% block body %}
    <h1>{{ employe}}</h1>
    <p>
        ville : {{ employe.ville}} <br>
        entreprise : <a href="{{ path( 'show_entreprise', {'id': employe.entreprise.id} )}}">{{ employe.entreprise}}</a> <br>
        date d'embauche : {{ employe.dateEmbauche | date('d-m-Y')}} <br>
        date naisssance : {{ employe.datenaissance | date('d-m-Y')}} ( {{ employe.age}} ans )<br>
    </p>
    
{% endblock %}